apiVersion: v2
name: microbin
description: Microbin - File sharing made easy
type: application
version: 0.2.0
appVersion: "2.1.0"
home: "https://github.com/james-otten/microbin-helm"
sources: ["https://github.com/james-otten/microbin-helm"]
icon: https://microbin.eu/img/logo-square.png
maintainers:
  - email: info@jamesotten.com
    name: james-otten
